version: '3.8'

services:
  wab-backend:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      target: backend-runtime
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3004
      DATABASE_URI: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      SESSION_SECRET: "${SESSION_SECRET}"
      REACT_APP_PUBLIC_URL: "http://localhost"
      HOST: "http://localhost"
    networks:
      - plasmic-net
    depends_on:
      - db

  wab-frontend:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      target: frontend-runtime
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - wab-backend
    networks:
      - plasmic-net

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - plasmic-net
    restart: always

networks:
  plasmic-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/plasmic/postgres_data
