services:
  plasmic-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER} -d ${DB_NAME}'
      interval: 5s
      timeout: 10s
      retries: 5

  plasmic-wab:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      target: runtime
    restart: always
    ports:
      - 3003:3003
      - 3004:3004
      - 3005:3005
    depends_on:
      plasmic-db:
        condition: service_healthy
    environment:
      - DATABASE_URI=postgres://${DB_USER}:${DB_PASSWORD}@plasmic-db:5432/${DB_NAME}
      - WAB_DBNAME=${DB_NAME}
      - WAB_DBPASSWORD=${DB_PASSWORD}
      - NODE_ENV=development
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_HOST=plasmic-db
      - CHOKIDAR_USEPOLLING=true
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/plasmic/postgres_data
